### ISSUE TITLE
Repository is ready

### ISSUE THREAD

**Issue by canimiranti** [quarcs-lab/tutorial-spatial-regression-stata#1]
Dear Sensei @cmg777,

I have moved the repository to Quarcs-lab account and update the Rmd. Now, it's ready if you want to publish it at Zenodo.
Thank you.

Best regards,
Cani

**Comment by cmg777** [comment]
Ok, the repository is ready. I created and added the Zenodo DOI to the README file
[![DOI](https://zenodo.org/badge/341060589.svg)](https://zenodo.org/badge/latestdoi/341060589)

**Comment by cmg777** [comment]
Ok Cani. It is published now

Kind regards,

Carlos  Mendez
Associate Professor
Graduate School of International Development
Nagoya University, JAPAN
—————————————————————————————
Website:  carlos-mendez.rbind.io
Research lab:  QuaRCS-lab.org <http://quarcs-lab.org>
E-mail:  carlos@gsid.nagoya-u.ac.jp
Phone:  +81-052-789-4345
—————————————————————————————
